"use client";

import { useState } from "react";
import {
  FileText,
  Download,
  Calendar,
  Filter,
  CheckCircle2,
  Clock,
  FileSpreadsheet,
  AlertTriangle,
  RefreshCw,
  Search,
  HardDrive,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface ReportItem {
  id: string;
  title: string;
  category: "Safety & Hazard" | "Emergency SOS" | "Vessel & Compliance" | "Oceanographic";
  description: string;
  lastGenerated: string;
  fileFormat: string;
  fileSize: string;
  status: "Ready" | "Generating" | "Scheduled";
}

const MOCK_REPORTS: ReportItem[] = [
  {
    id: "REP-2026-091",
    title: "Daily Coastal Hazard & Broadcast Summary",
    category: "Safety & Hazard",
    description: "Consolidated log of active high-wave warnings, sea surface anomalies, and broadcast dispatches sent across Kerala & Lakshadweep coastal sectors.",
    lastGenerated: "Today, 06:00 AM",
    fileFormat: "PDF",
    fileSize: "3.4 MB",
    status: "Ready",
  },
  {
    id: "REP-2026-092",
    title: "SOS Distress Incident Logbook",
    category: "Emergency SOS",
    description: "Complete chronological telemetry audit of emergency SOS signals, GPS coordinates, response dispatch times, and Coast Guard intervention status.",
    lastGenerated: "Yesterday, 11:30 PM",
    fileFormat: "PDF",
    fileSize: "1.8 MB",
    status: "Ready",
  },
  {
    id: "REP-2026-093",
    title: "Weekly Maritime Compliance & Geofence Report",
    category: "Vessel & Compliance",
    description: "Statistical breakdown of territorial boundary incursions, international maritime boundary line (IMBL) proximity warnings, and vessel compliance ratings.",
    lastGenerated: "Sep 15, 2026",
    fileFormat: "PDF / CSV",
    fileSize: "5.1 MB",
    status: "Ready",
  },
  {
    id: "REP-2026-094",
    title: "Fleet Safety Audit & AIS Telemetry Digest",
    category: "Vessel & Compliance",
    description: "Operational status of active registered fishing craft, AIS transponder active hours, and coastal patrol coverage density across South-West Maritime Zones.",
    lastGenerated: "Sep 12, 2026",
    fileFormat: "PDF",
    fileSize: "4.2 MB",
    status: "Ready",
  },
  {
    id: "REP-2026-095",
    title: "Monthly Ocean Surface Temperature & Current Analysis",
    category: "Oceanographic",
    description: "Multi-week INCOIS satellite telemetry summary including sea surface temperature anomalies, wave height spectrum trends, and fish catch correlation models.",
    lastGenerated: "Sep 01, 2026",
    fileFormat: "PDF",
    fileSize: "8.6 MB",
    status: "Ready",
  },
  {
    id: "REP-2026-096",
    title: "Automated Bhashini Advisory Broadcast Ledger",
    category: "Safety & Hazard",
    description: "Multilingual translation audit trail logging Malayalam, Tamil, and Hindi advisory broadcasts generated by ORCA AI agent pipeline.",
    lastGenerated: "Today, 02:00 AM",
    fileFormat: "CSV",
    fileSize: "920 KB",
    status: "Ready",
  },
];

export default function OfficialReportsAnalyticsPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const filteredReports = MOCK_REPORTS.filter((rep) => {
    const matchesSearch =
      rep.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rep.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory =
      selectedCategory === "All" || rep.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const handleDownload = (id: string, title: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      setDownloadingId(null);
      alert(`Simulated PDF download initiated for: "${title}"`);
    }, 1200);
  };

  return (
    <div className="space-y-6">
      {/* Title Header */}
      <section className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-cyan-50 border border-cyan-200 text-cyan-800 text-[11px] font-semibold mb-2 shadow-sm">
            <FileText className="h-3 w-3 text-cyan-700" />
            Official Patrol & Incident Records
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">
            Reports & Analytics
          </h1>
          <p className="text-xs md:text-sm text-slate-600 mt-0.5">
            Downloadable daily hazard summaries, emergency distress logbooks, and coastal compliance analytics.
          </p>
        </div>
        <Button className="bg-cyan-700 hover:bg-cyan-600 text-white font-semibold text-xs shadow-sm flex items-center gap-2 shrink-0">
          <RefreshCw className="h-4 w-4" />
          Generate Custom Report
        </Button>
      </section>

      {/* Overview Stat Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-50 text-cyan-700 border border-cyan-100">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <div className="text-xl font-extrabold text-slate-900">142</div>
              <div className="text-xs text-slate-500 font-medium">Reports Generated (Sep)</div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-amber-50 text-amber-700 border border-amber-100">
              <Clock className="h-5 w-5" />
            </div>
            <div>
              <div className="text-xl font-extrabold text-amber-700">3 Pending</div>
              <div className="text-xs text-slate-500 font-medium">Command Reviews</div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-emerald-50 text-emerald-700 border border-emerald-100">
              <CheckCircle2 className="h-5 w-5" />
            </div>
            <div>
              <div className="text-xl font-extrabold text-slate-900">8 Active</div>
              <div className="text-xs text-slate-500 font-medium">Automated Schedules</div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-slate-100 text-slate-700 border border-slate-200">
              <HardDrive className="h-5 w-5" />
            </div>
            <div>
              <div className="text-xl font-extrabold text-slate-900">1.4 GB</div>
              <div className="text-xs text-slate-500 font-medium">Archival Storage Used</div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search & Category Filter Toolbar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-white p-3 rounded-xl border border-slate-200 shadow-sm">
        <div className="relative w-full sm:w-80">
          <Search className="h-3.5 w-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <Input
            placeholder="Search report titles or keywords..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-8 text-xs bg-slate-50 border-slate-200 h-8"
          />
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
          <Filter className="h-3.5 w-3.5 text-slate-500" />
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="text-xs border border-slate-200 bg-slate-50 rounded-lg px-2.5 h-8 text-slate-700 font-medium focus:outline-none focus:ring-1 focus:ring-cyan-500"
          >
            <option value="All">All Categories</option>
            <option value="Safety & Hazard">Safety & Hazard</option>
            <option value="Emergency SOS">Emergency SOS</option>
            <option value="Vessel & Compliance">Vessel & Compliance</option>
            <option value="Oceanographic">Oceanographic</option>
          </select>
        </div>
      </div>

      {/* Grid of Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredReports.map((report) => (
          <Card
            key={report.id}
            className="bg-white border-slate-200 text-slate-900 shadow-sm hover:border-cyan-400 transition-all flex flex-col justify-between"
          >
            <CardHeader className="pb-3 border-b border-slate-100">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <div className="p-2 rounded-lg bg-cyan-50 border border-cyan-200 text-cyan-700 shrink-0">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div>
                    <CardTitle className="text-sm font-bold text-slate-900 leading-snug">
                      {report.title}
                    </CardTitle>
                    <div className="text-[11px] text-slate-400 font-mono mt-0.5">
                      ID: {report.id}
                    </div>
                  </div>
                </div>

                <Badge
                  variant="outline"
                  className={`text-[10px] font-semibold px-2 py-0.5 shrink-0 ${
                    report.category === "Emergency SOS"
                      ? "bg-red-50 text-red-700 border-red-200"
                      : report.category === "Safety & Hazard"
                      ? "bg-amber-50 text-amber-800 border-amber-200"
                      : report.category === "Oceanographic"
                      ? "bg-blue-50 text-blue-700 border-blue-200"
                      : "bg-slate-50 text-slate-700 border-slate-200"
                  }`}
                >
                  {report.category}
                </Badge>
              </div>
            </CardHeader>

            <CardContent className="pt-3 space-y-4 flex-1 flex flex-col justify-between">
              <CardDescription className="text-xs text-slate-600 leading-relaxed">
                {report.description}
              </CardDescription>

              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500 font-mono">
                <div className="flex items-center gap-1.5 text-[11px]">
                  <Calendar className="h-3.5 w-3.5 text-slate-400" />
                  <span>{report.lastGenerated}</span>
                </div>

                <div className="text-[11px] font-semibold text-slate-700">
                  {report.fileFormat} • {report.fileSize}
                </div>
              </div>

              <div className="flex items-center gap-2 pt-1">
                <Button
                  onClick={() => handleDownload(report.id, report.title)}
                  disabled={downloadingId === report.id}
                  size="sm"
                  className="w-full bg-cyan-700 hover:bg-cyan-600 text-white font-semibold text-xs shadow-sm flex items-center justify-center gap-2 h-9"
                >
                  <Download className={`h-3.5 w-3.5 ${downloadingId === report.id ? "animate-bounce" : ""}`} />
                  {downloadingId === report.id ? "Downloading..." : "Download PDF"}
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
