"use client";

import { useState } from "react";
import { ShieldCheck, MapPin, ShieldAlert, Layers } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import LeafletMap, { MapMarker, HeatPoint } from "@/components/map/LeafletMap";

const REGIONAL_MAP_CENTER = { lat: 9.9312, lng: 76.2673 };

export default function OfficialGeofencingPage() {
  const [markers] = useState<MapMarker[]>([
    { lat: 9.9312, lng: 76.2673, label: "Coast Guard Base", icon: "landing" },
    { lat: 9.85, lng: 76.05, label: "IMBL Restricted Buffer Boundary", icon: "boat" },
    { lat: 9.98, lng: 76.22, label: "Commercial Shipping Channel Entrance", icon: "boat" },
  ]);

  const [heatPoints] = useState<HeatPoint[]>([
    { lat: 9.975, lng: 76.18, intensity: 0.95 },
    { lat: 9.85, lng: 76.05, intensity: 0.1 },
    { lat: 9.98, lng: 76.22, intensity: 0.35 },
  ]);

  const BOUNDARY_ZONES = [
    {
      id: "GEO-01",
      name: "International Maritime Boundary Line (IMBL 24nm Buffer)",
      status: "Active Surveillance",
      type: "International Border Buffer",
      vesselsNearby: 3,
      restriction: "Strict Prohibited Entry for Commercial Trawlers",
      badgeVariant: "destructive" as const,
    },
    {
      id: "GEO-02",
      name: "Cochin Port Outer Entrance Channel (Fairway Sector)",
      status: "Channel Monitoring",
      type: "Navigational Shipping Lane",
      vesselsNearby: 7,
      restriction: "No Fishing / Keep 500m Channel Clearance",
      badgeVariant: "warning" as const,
    },
    {
      id: "GEO-03",
      name: "Chellanam Marine Sanctuary & Coral Reef Buffer",
      status: "Ecological Reserve",
      type: "Conservation Zone",
      vesselsNearby: 0,
      restriction: "Bottom Trawling & Net Dredging Banned",
      badgeVariant: "warning" as const,
    },
    {
      id: "GEO-04",
      name: "Munambam Coastal Patrol Sector",
      status: "Patrol Active",
      type: "Security Sector",
      vesselsNearby: 12,
      restriction: "Standard Coastal Registration Required",
      badgeVariant: "success" as const,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Title Header */}
      <section className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-cyan-50 border border-cyan-200 text-cyan-800 text-[11px] font-semibold mb-2 shadow-sm">
            <ShieldCheck className="h-3 w-3 text-cyan-700" />
            Turf.js GeoJSON Boundary Engine
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">
            Geofencing & Maritime Boundaries
          </h1>
          <p className="text-xs md:text-sm text-slate-600 mt-0.5">
            Active tracking of international maritime boundary lines, commercial shipping lanes, and marine conservation zones.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Badge className="bg-cyan-50 text-cyan-800 border-cyan-200 px-3 py-1 text-xs">
            4 Geofence Zones Active
          </Badge>
        </div>
      </section>

      {/* Map Section */}
      <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
        <CardHeader className="border-b border-slate-100 pb-3 flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <MapPin className="h-5 w-5 text-emerald-600" />
              Boundary Geofence Map Overlay
            </CardTitle>
            <CardDescription className="text-xs text-slate-500 mt-0.5">
              Red surface gradient indicates restricted boundary zones; Green indicates allowed fishing sectors.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent className="p-4">
          <LeafletMap
            center={REGIONAL_MAP_CENTER}
            zoom={9}
            className="h-80 w-full rounded-xl"
            markers={markers}
            heatPoints={heatPoints}
          />
        </CardContent>
      </Card>

      {/* Tracked Boundary Zones List */}
      <Card className="bg-white border-slate-200 text-slate-900 shadow-sm">
        <CardHeader className="border-b border-slate-100 pb-3">
          <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-cyan-700" />
            Tracked Maritime Geofence Zones
          </CardTitle>
          <CardDescription className="text-xs text-slate-500">
            Real-time proximity warnings generated by Turf.js spatial analysis
          </CardDescription>
        </CardHeader>
        <CardContent className="p-4 space-y-3">
          {BOUNDARY_ZONES.map((zone) => (
            <div
              key={zone.id}
              className="p-4 rounded-xl bg-slate-50 border border-slate-200 flex flex-col md:flex-row md:items-center justify-between gap-3"
            >
              <div className="flex items-start gap-3">
                <div className="p-2.5 rounded-xl bg-white border border-slate-200 text-cyan-700 shrink-0">
                  <ShieldCheck className="h-5 w-5" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-900 text-sm">{zone.name}</span>
                    <Badge variant={zone.badgeVariant as any} className="text-[10px] px-2 py-0">
                      {zone.type}
                    </Badge>
                    <span className="text-[11px] font-mono text-slate-400">({zone.id})</span>
                  </div>
                  <p className="text-xs text-slate-600 mt-1">
                    Restriction Rule: <span className="text-slate-900 font-medium">{zone.restriction}</span>
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-4 text-xs shrink-0 self-end md:self-auto">
                <div className="text-right">
                  <div className="text-slate-500 text-[11px]">Vessels Nearby</div>
                  <div className="font-bold text-slate-900">{zone.vesselsNearby} craft</div>
                </div>
                <Badge variant="outline" className="bg-emerald-50 text-emerald-800 border-emerald-200">
                  {zone.status}
                </Badge>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
